In [1]:
import pandas as pd

df = pd.read_csv('/Users/atulyaagrawal/Desktop/steam_top_games_2026.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1495 entries, 0 to 1494
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   app_id                1495 non-null   int64
 1   name                  1495 non-null   object
 2   release_date          1488 non-null   object
 3   coming_soon           1495 non-null   bool
 4   price_usd             1495 non-null   float64
 5   is_free               1495 non-null   bool
 6   discount_pct          1495 non-null   int64
 7   developer             1487 non-null   object
 8   publisher             1483 non-null   object
 9   genres                1487 non-null   object
 10  categories            1486 non-null   object
 11  tags                  1489 non-null   object
 12  platforms_win         1495 non-null   bool
 13  platforms_mac         1495 non-null   bool
 14  platforms_linux       1495 non-null   bool
 15  metacritic_score      540 non-null    float64
 16  recommendations       1495 non-null   int64
 17  positive_reviews      1495 non-null   int64
 18  negative_reviews      1495 non-null   int64
 19  estimated_owners      1490 non-null   object
 20  avg_playtime_forever  1495 non-null   int64
 21  avg_playtime_2weeks   1495 non-null   int64
 22  median_playtime       1495 non-null   int64
 23  peak_ccu              1495 non-null   int64
 24  required_age          1495 non-null   int64
 25  dlc_count             1495 non-null   int64
 26  achievements          1495 non-null   int64
 27  short_description     1493 non-null   object
 28  header_image          1494 non-null   object
dtypes: bool(5), float64(2), int64(12), object(10)
memory usage: 287.7+ KB

In [2]:
df.head(5)

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
0,794260,Outward Definitive Edition,"May 17, 2022",False,4.79,False,88,Nine Dots Studio,"Prime Matter, Deep Silver",RPG,...,"1,000,000 .. 2,000,000",1332,824,465,469,0,1,72,No remarkable journey is achieved without grea...,https://shared.akamai.steamstatic.com/store_it...
1,253920,Gorky 17,"Sep 27, 2013",False,9.99,False,0,Metropolis Software,TopWare Interactive,"RPG, Strategy",...,"200,000 .. 500,000",301,0,328,61,17,2,0,November 2008. NATO intelligence services repo...,https://shared.akamai.steamstatic.com/store_it...
2,613010,Secret in Story,"Jun 19, 2017",False,0.89,False,10,Naivus Luo,Naivus Luo,"Adventure, Indie",...,"2,000,000 .. 5,000,000",251,0,243,0,0,0,32,"Accompanied by beautiful piano music, you begi...",https://shared.akamai.steamstatic.com/store_it...
3,892420,懒人修仙传,"Nov 14, 2018",False,3.99,False,0,托更的修罗,托更的修罗,"Casual, Indie, RPG, Simulation",...,"200,000 .. 500,000",5786,0,9223,41,0,0,0,这是一款很&quot;休闲&quot;的文字挂机游戏，游戏小而系统完善，玩法丰富，极其耗电，...,https://shared.akamai.steamstatic.com/store_it...
4,914010,Train Station Renovation,"Oct 1, 2020",False,18.99,False,0,Live Motion Games,"Live Motion Games, Frozen Way, PlayWay S.A., F...","Casual, Indie, Simulation",...,"200,000 .. 500,000",448,0,201,16,0,1,73,"Welcome to an old, ruined train station. A pla...",https://shared.akamai.steamstatic.com/store_it...

In [7]:
print(len(df))

1495

In [9]:
print(df.columns)

Index(['app_id', 'name', 'release_date', 'coming_soon', 'price_usd', 'is_free',
       'discount_pct', 'developer', 'publisher', 'genres', 'categories',
       'tags', 'platforms_win', 'platforms_mac', 'platforms_linux',
       'metacritic_score', 'recommendations', 'positive_reviews',
       'negative_reviews', 'estimated_owners', 'avg_playtime_forever',
       'avg_playtime_2weeks', 'median_playtime', 'peak_ccu', 'required_age',
       'dlc_count', 'achievements', 'short_description', 'header_image'],
      dtype='object')

In [10]:
print(df.dtypes)

app_id                    int64
name                     object
release_date             object
coming_soon                bool
price_usd               float64
is_free                    bool
discount_pct              int64
developer                object
publisher                object
genres                   object
categories               object
tags                     object
platforms_win              bool
platforms_mac              bool
platforms_linux            bool
metacritic_score        float64
recommendations           int64
positive_reviews          int64
negative_reviews          int64
estimated_owners         object
avg_playtime_forever      int64
avg_playtime_2weeks       int64
median_playtime           int64
peak_ccu                  int64
required_age              int64
dlc_count                 int64
achievements              int64
short_description        object
header_image             object
dtype: object

In [11]:
df.head(10)

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
0,794260,Outward Definitive Edition,"May 17, 2022",False,4.79,False,88,Nine Dots Studio,"Prime Matter, Deep Silver",RPG,...,"1,000,000 .. 2,000,000",1332,824,465,469,0,1,72,No remarkable journey is achieved without grea...,https://shared.akamai.steamstatic.com/store_it...
1,253920,Gorky 17,"Sep 27, 2013",False,9.99,False,0,Metropolis Software,TopWare Interactive,"RPG, Strategy",...,"200,000 .. 500,000",301,0,328,61,17,2,0,November 2008. NATO intelligence services repo...,https://shared.akamai.steamstatic.com/store_it...
2,613010,Secret in Story,"Jun 19, 2017",False,0.89,False,10,Naivus Luo,Naivus Luo,"Adventure, Indie",...,"2,000,000 .. 5,000,000",251,0,243,0,0,0,32,"Accompanied by beautiful piano music, you begi...",https://shared.akamai.steamstatic.com/store_it...
3,892420,懒人修仙传,"Nov 14, 2018",False,3.99,False,0,托更的修罗,托更的修罗,"Casual, Indie, RPG, Simulation",...,"200,000 .. 500,000",5786,0,9223,41,0,0,0,这是一款很&quot;休闲&quot;的文字挂机游戏，游戏小而系统完善，玩法丰富，极其耗电，...,https://shared.akamai.steamstatic.com/store_it...
4,914010,Train Station Renovation,"Oct 1, 2020",False,18.99,False,0,Live Motion Games,"Live Motion Games, Frozen Way, PlayWay S.A., F...","Casual, Indie, Simulation",...,"200,000 .. 500,000",448,0,201,16,0,1,73,"Welcome to an old, ruined train station. A pla...",https://shared.akamai.steamstatic.com/store_it...
5,352550,Urban Empire,"Jan 20, 2017",False,2.99,False,90,Reborn Games,Kalypso Media Digital,"Simulation, Strategy",...,"200,000 .. 500,000",114,0,104,3,0,0,74,"Urban Empire is a ‘City Ruler’, pioneering a n...",https://shared.akamai.steamstatic.com/store_it...
6,247020,"Cook, Serve, Delicious!","Oct 8, 2013",False,12.99,False,0,Vertigo Gaming Inc.,Vertigo Gaming Inc.,"Action, Indie, Simulation, Strategy",...,"500,000 .. 1,000,000",491,0,233,7,0,1,52,Hungry? Take your restaurant from a one star a...,https://shared.akamai.steamstatic.com/store_it...
7,253940,Septerra Core,"Sep 27, 2013",False,7.99,False,0,NaN,Topware Interactive,RPG,...,"200,000 .. 500,000",348,0,300,4,0,2,0,"At the very heart of Septerra lies the Core, a...",https://shared.akamai.steamstatic.com/store_it...
8,1846170,Iron Lung,"Mar 9, 2022",False,7.99,False,0,David Szymanski,David Szymanski,"Adventure, Indie, Simulation",...,"200,000 .. 500,000",84,0,83,3,0,1,7,A short horror game where you pilot a tiny sub...,https://shared.akamai.steamstatic.com/store_it...
9,260210,Assassin’s Creed® Liberation HD,"Jan 15, 2014",False,19.99,False,0,Ubisoft Sofia,Ubisoft,"Action, Adventure",...,"200,000 .. 500,000",265,0,113,6,17,0,30,"Introducing Assassin’s Creed® Liberation HD, t...",https://shared.akamai.steamstatic.com/store_it...

In [15]:
df.isnull().sum()

app_id                  0
name                    0
release_date            0
coming_soon             0
price_usd               0
is_free                 0
discount_pct            0
developer               0
publisher               0
genres                  0
categories              0
tags                    0
platforms_win           0
platforms_mac           0
platforms_linux         0
metacritic_score        0
recommendations         0
positive_reviews        0
negative_reviews        0
estimated_owners        0
avg_playtime_forever    0
avg_playtime_2weeks     0
median_playtime         0
peak_ccu                0
required_age            0
dlc_count               0
achievements            0
short_description       0
header_image            0
dtype: int64

In [16]:
df.head(5)

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
4,914010,Train Station Renovation,"Oct 1, 2020",False,18.99,False,0,Live Motion Games,"Live Motion Games, Frozen Way, PlayWay S.A., F...","Casual, Indie, Simulation",...,"200,000 .. 500,000",448,0,201,16,0,1,73,"Welcome to an old, ruined train station. A pla...",https://shared.akamai.steamstatic.com/store_it...
5,352550,Urban Empire,"Jan 20, 2017",False,2.99,False,90,Reborn Games,Kalypso Media Digital,"Simulation, Strategy",...,"200,000 .. 500,000",114,0,104,3,0,0,74,"Urban Empire is a ‘City Ruler’, pioneering a n...",https://shared.akamai.steamstatic.com/store_it...
11,34330,Total War: SHOGUN 2,"Mar 15, 2011",False,5.99,False,80,"CREATIVE ASSEMBLY, Feral Interactive (Mac), Fe...","SEGA, Feral Interactive (Mac), Feral Interacti...",Strategy,...,"2,000,000 .. 5,000,000",2536,828,402,1807,0,8,106,Total War: SHOGUN 2 is the perfect mix of real...,https://shared.akamai.steamstatic.com/store_it...
13,736260,Baba Is You,"Mar 13, 2019",False,14.99,False,0,Hempuli Oy,Hempuli Oy,Indie,...,"1,000,000 .. 2,000,000",813,120,317,269,0,1,18,Baba Is You is a puzzle game where the rules y...,https://shared.akamai.steamstatic.com/store_it...
15,350640,Sherlock Holmes: The Devil's Daughter,"Jun 10, 2016",False,2.99,False,90,Frogwares,Frogwares,"Action, Adventure",...,"1,000,000 .. 2,000,000",322,0,200,21,0,1,25,Experience a fantastic adventure with unique g...,https://shared.akamai.steamstatic.com/store_it...

In [20]:
print(df['price_usd'].mean())

16.274800000000003

In [22]:
print('Maximum price: ', df['price_usd'].max())
print('Minimum price: ', df['price_usd'].min())

Maximum price:  69.99
Minimum price:  0.0

In [24]:
df.head(5)

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
4,914010,Train Station Renovation,"Oct 1, 2020",False,18.99,False,0,Live Motion Games,"Live Motion Games, Frozen Way, PlayWay S.A., F...","Casual, Indie, Simulation",...,"200,000 .. 500,000",448,0,201,16,0,1,73,"Welcome to an old, ruined train station. A pla...",https://shared.akamai.steamstatic.com/store_it...
5,352550,Urban Empire,"Jan 20, 2017",False,2.99,False,90,Reborn Games,Kalypso Media Digital,"Simulation, Strategy",...,"200,000 .. 500,000",114,0,104,3,0,0,74,"Urban Empire is a ‘City Ruler’, pioneering a n...",https://shared.akamai.steamstatic.com/store_it...
11,34330,Total War: SHOGUN 2,"Mar 15, 2011",False,5.99,False,80,"CREATIVE ASSEMBLY, Feral Interactive (Mac), Fe...","SEGA, Feral Interactive (Mac), Feral Interacti...",Strategy,...,"2,000,000 .. 5,000,000",2536,828,402,1807,0,8,106,Total War: SHOGUN 2 is the perfect mix of real...,https://shared.akamai.steamstatic.com/store_it...
13,736260,Baba Is You,"Mar 13, 2019",False,14.99,False,0,Hempuli Oy,Hempuli Oy,Indie,...,"1,000,000 .. 2,000,000",813,120,317,269,0,1,18,Baba Is You is a puzzle game where the rules y...,https://shared.akamai.steamstatic.com/store_it...
15,350640,Sherlock Holmes: The Devil's Daughter,"Jun 10, 2016",False,2.99,False,90,Frogwares,Frogwares,"Action, Adventure",...,"1,000,000 .. 2,000,000",322,0,200,21,0,1,25,Experience a fantastic adventure with unique g...,https://shared.akamai.steamstatic.com/store_it...

In [29]:
df['is_free'].sum()

np.int64(22)

In [32]:
df.sort_values('price_usd',ascending=False).head(1)

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
155,2072450,Like a Dragon: Infinite Wealth,"Jan 25, 2024",False,69.99,False,0,Ryu Ga Gotoku Studio,SEGA,"Action, Adventure, RPG",...,"500,000 .. 1,000,000",3635,63,2029,655,17,19,74,"Two larger-than-life heroes, Ichiban Kasuga an...",https://shared.akamai.steamstatic.com/store_it...

In [33]:
df.sort_values('price_usd',ascending=True).head(1)

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
200,255420,Magic 2015 - Duels of the Planeswalkers,"Jul 16, 2014",False,0.0,False,0,Stainless Games,Wizards of the Coast,Strategy,...,"200,000 .. 500,000",1535,0,301,2,0,0,35,&quot;Hunt bigger game on a bold new adventure...,https://shared.akamai.steamstatic.com/store_it...

In [35]:
df[df['price_usd'] > 50]

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
73,2677660,Indiana Jones and the Great Circle,"Dec 8, 2024",False,69.99,False,0,MachineGames,Bethesda Softworks,"Action, Adventure",...,"200,000 .. 500,000",1411,0,1331,274,0,1,55,Uncover one of history’s greatest mysteries in...,https://shared.akamai.steamstatic.com/store_it...
155,2072450,Like a Dragon: Infinite Wealth,"Jan 25, 2024",False,69.99,False,0,Ryu Ga Gotoku Studio,SEGA,"Action, Adventure, RPG",...,"500,000 .. 1,000,000",3635,63,2029,655,17,19,74,"Two larger-than-life heroes, Ichiban Kasuga an...",https://shared.akamai.steamstatic.com/store_it...
193,1086940,Baldur's Gate 3,"Aug 3, 2023",False,59.99,False,0,Larian Studios,Larian Studios,"Adventure, RPG, Strategy",...,"20,000,000 .. 50,000,000",7794,685,4392,54771,17,2,54,"Baldur’s Gate 3 is a story-rich, party-based R...",https://shared.akamai.steamstatic.com/store_it...
232,814380,Sekiro™: Shadows Die Twice - GOTY Edition,"Mar 21, 2019",False,59.99,False,0,"FromSoftware, Inc.","Activision (Excluding Japan and Asia), FromSof...","Action, Adventure",...,"10,000,000 .. 20,000,000",2734,42,1583,6767,17,0,34,Game of the Year - The Game Awards 2019 Best A...,https://shared.akamai.steamstatic.com/store_it...
361,1382330,Persona® 5 Strikers,"Feb 22, 2021",False,59.99,False,0,ATLUS,SEGA,"Action, Adventure",...,"1,000,000 .. 2,000,000",995,0,454,199,17,2,47,Join the Phantom Thieves and strike back again...,https://shared.akamai.steamstatic.com/store_it...
771,1778820,TEKKEN 8,"Jan 25, 2024",False,59.99,False,0,Bandai Namco Studios Inc.,Bandai Namco Entertainment,Action,...,"1,000,000 .. 2,000,000",5647,350,1605,4409,0,22,47,TEKKEN 8 is the latest addition to the TEKKEN ...,https://shared.akamai.steamstatic.com/store_it...
822,209650,Call of Duty®: Advanced Warfare - Gold Edition,"Nov 3, 2014",False,59.99,False,0,"Sledgehammer Games, Raven Software",Activision,Action,...,"200,000 .. 500,000",506,34,413,63,17,43,45,Call of Duty®: Advanced Warfare envisions a po...,https://shared.akamai.steamstatic.com/store_it...
1134,916440,Anno 1800,"Apr 16, 2019",False,59.99,False,0,Ubisoft Mainz,Ubisoft,"Simulation, Strategy",...,"1,000,000 .. 2,000,000",1805,181,480,2784,0,35,112,Anno 1800™ – Lead the Industrial Revolution! W...,https://shared.akamai.steamstatic.com/store_it...
1220,924970,Back 4 Blood,"Oct 12, 2021",False,59.99,False,0,Turtle Rock Studios,Warner Bros. Games,Action,...,"1,000,000 .. 2,000,000",1558,52,607,1288,17,4,93,Back 4 Blood is a thrilling cooperative first-...,https://shared.akamai.steamstatic.com/store_it...
1252,544750,SOULCALIBUR VI,"Oct 18, 2018",False,59.99,False,0,"BANDAI NAMCO Studios Inc., Dimps Corporation",BANDAI NAMCO Entertainment,Action,...,"1,000,000 .. 2,000,000",502,69,126,119,0,16,49,Bring more than your fists to the fight! Featu...,https://shared.akamai.steamstatic.com/store_it...
1255,1771300,Kingdom Come: Deliverance II,"Feb 4, 2025",False,59.99,False,0,Warhorse Studios,Deep Silver,"Action, Adventure, RPG",...,"2,000,000 .. 5,000,000",4594,944,3697,7073,18,10,83,"A thrilling story-driven action RPG, with a ri...",https://shared.akamai.steamstatic.com/store_it...
1295,898750,Super Robot Wars 30,"Oct 27, 2021",False,59.99,False,0,Bandai Namco Forge Digitals Inc.,Bandai Namco Entertainment,"RPG, Simulation, Strategy",...,"500,000 .. 1,000,000",2765,0,1674,283,0,6,38,"30 years on, the battle for our world's future...",https://shared.akamai.steamstatic.com/store_it...

In [38]:
df[df['is_free'] == True]

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
101,200390,Oil Rush,"Jan 25, 2012",False,0.0,True,0,Unigine Corp.,Unigine Corp.,"Indie, Strategy",...,"200,000 .. 500,000",128,0,29,0,0,2,40,Oil Rush is a naval strategy game that takes p...,https://shared.akamai.steamstatic.com/store_it...
216,9880,Champions Online,"Jun 14, 2011",False,0.0,True,0,Cryptic Studios,Arc Games,"Massively Multiplayer, RPG, Free To Play",...,"500,000 .. 1,000,000",931,0,160,113,0,0,709,Grab your cape and defend Millennium City in t...,https://shared.akamai.steamstatic.com/store_it...
355,298260,Only If,"Jul 25, 2014",False,0.0,True,0,Creability,Creability,"Adventure, Indie, Free To Play",...,"500,000 .. 1,000,000",90,0,44,2,0,0,10,Only If is a surreal first person adventure-pu...,https://shared.akamai.steamstatic.com/store_it...
564,377300,Thunder Tier One,"Dec 7, 2021",False,0.0,True,0,"KRAFTON, Inc.","KRAFTON, Inc.","Action, Simulation, Free To Play",...,"1,000,000 .. 2,000,000",165,0,92,102,0,0,36,Thunder Tier One is a realistic top-down shoot...,https://shared.akamai.steamstatic.com/store_it...
608,386360,SMITE®,"Sep 8, 2015",False,0.0,True,0,Titan Forge Games,Hi-Rez Studios,"Action, Adventure, Casual, Indie, Massively Mu...",...,"10,000,000 .. 20,000,000",8170,492,280,1853,0,13,319,"Join 40+ million players in SMITE, the Battleg...",https://shared.akamai.steamstatic.com/store_it...
610,230410,Warframe,"Mar 25, 2013",False,0.0,True,0,Digital Extremes,Digital Extremes,"Action, RPG, Free To Play",...,"20,000,000 .. 50,000,000",14399,1056,550,36195,17,17,193,Awaken as an unstoppable warrior and battle al...,https://shared.akamai.steamstatic.com/store_it...
663,24200,DC Universe™ Online,"Nov 2, 2011",False,0.0,True,0,Dimensional Ink Games,Daybreak Game Company,"Action, Adventure, Massively Multiplayer, RPG,...",...,"1,000,000 .. 2,000,000",2323,0,601,546,0,2,202,"DC Universe Online is a Free-to-Play, massive ...",https://shared.akamai.steamstatic.com/store_it...
664,311730,DEAD OR ALIVE 5 Last Round: Core Fighters,"Mar 30, 2015",False,0.0,True,0,"Team NINJA, KOEI TECMO GAMES CO., LTD.","KOEI TECMO GAMES CO., LTD.",Action,...,"500,000 .. 1,000,000",270,0,28,36,17,62,45,The free version of the final word in fighting...,https://shared.akamai.steamstatic.com/store_it...
701,9900,Star Trek Online,"Jan 31, 2012",False,0.0,True,0,Cryptic Studios,Arc Games,"Massively Multiplayer, RPG, Free To Play",...,"2,000,000 .. 5,000,000",9410,19,411,1057,0,0,0,"In Star Trek Online, the Star Trek universe ap...",https://shared.akamai.steamstatic.com/store_it...
739,212070,Star Conflict,"Feb 27, 2013",False,0.0,True,0,Star Gem Inc.,Gaijin Network Ltd,"Action, Adventure, Massively Multiplayer, RPG,...",...,"2,000,000 .. 5,000,000",1523,0,132,95,0,81,213,"Star Conflict is an action-packed, massively m...",https://shared.akamai.steamstatic.com/store_it...
811,298520,Orbital Gear,"Aug 7, 2014",False,0.0,True,0,Night Node,Night Node,"Action, Indie, Simulation, Free To Play",...,"200,000 .. 500,000",163,0,107,0,0,1,12,Orbital Gear is a fast paced sidescroller shoo...,https://shared.akamai.steamstatic.com/store_it...
864,225600,Blade Symphony,"May 7, 2014",False,0.0,True,0,Puny Human,Puny Human,"Action, Indie",...,"500,000 .. 1,000,000",271,0,82,0,0,1,26,Prove you are the world's greatest swordsman! ...,https://shared.akamai.steamstatic.com/store_it...
982,238960,Path of Exile,"Oct 23, 2013",False,0.0,True,0,Grinding Gear Games,Grinding Gear Games,"Action, Adventure, Indie, Massively Multiplaye...",...,"20,000,000 .. 50,000,000",12914,2215,431,4694,0,6,127,"You are an Exile, struggling to survive on the...",https://shared.akamai.steamstatic.com/store_it...
1046,532840,CAYNE,"Jan 24, 2017",False,0.0,True,0,THE BROTHERHOOD,THE BROTHERHOOD,"Adventure, Indie, Free To Play",...,"200,000 .. 500,000",99,0,93,3,0,1,15,Hadley wakes in a facility. She is 9 months pr...,https://shared.akamai.steamstatic.com/store_it...
1078,293260,Card Hunter,"Jul 13, 2015",False,0.0,True,0,The Knights of Unity,The Knights of Unity,"RPG, Strategy, Free To Play",...,"500,000 .. 1,000,000",398,0,110,30,0,0,50,Shuffle your cards and ready your dice - Card ...,https://shared.akamai.steamstatic.com/store_it...
1222,39120,RIFT,"Mar 1, 2011",False,0.0,True,0,gamigo US Inc.,gamigo US Inc.,"Action, Adventure, Massively Multiplayer, RPG,...",...,"2,000,000 .. 5,000,000",5587,0,196,139,0,10,0,Dive into a world of epic adventure! Create yo...,https://shared.akamai.steamstatic.com/store_it...
1336,495910,Dungeon Fighter Online,"Aug 9, 2016",False,0.0,True,0,Neople,Neople,"Action, Adventure, Massively Multiplayer, RPG,...",...,"500,000 .. 1,000,000",817,0,205,173,0,2,156,Get ready for the ultimate brawl! Dungeon Figh...,https://shared.akamai.steamstatic.com/store_it...
1403,544920,Darwin Project,"Jan 13, 2020",False,0.0,True,0,Scavengers Studio,Scavengers Studio,"Action, Indie, Free To Play",...,"1,000,000 .. 2,000,000",357,0,76,0,0,0,14,"In Darwin Project, ten inmates must survive th...",https://shared.akamai.steamstatic.com/store_it...
1416,381640,Allods Online RU,"Jan 26, 2016",False,0.0,True,0,ASTRUM LAB,ASTRUM LAB,"Action, Massively Multiplayer, RPG, Free To Play",...,"200,000 .. 500,000",15810,0,1260,10,0,0,0,Tighten the ranks on your path to glorious vic...,https://shared.akamai.steamstatic.com/store_it...
1422,845070,The Awesome Adventures of Captain Spirit,"Jun 25, 2018",False,0.0,True,0,DONTNOD Entertainment,Square Enix,"Adventure, Free To Play",...,"2,000,000 .. 5,000,000",137,0,84,16,17,0,0,Have you ever dreamt of being a superhero? Mee...,https://shared.akamai.steamstatic.com/store_it...
1430,333930,Dirty Bomb®,"Jun 2, 2015",False,0.0,True,0,Splash Damage,Warchest Ltd.,"Action, Free To Play",...,"5,000,000 .. 10,000,000",792,0,87,40,0,0,77,Work together or die alone! Fight to restore p...,https://shared.akamai.steamstatic.com/store_it...
1445,227220,Sang-Froid - Tales of Werewolves,"Apr 5, 2013",False,0.0,True,0,Artifice Studio,Artifice Studio,"Action, Adventure, Indie, RPG, Strategy",...,"200,000 .. 500,000",81,0,66,0,0,0,33,"Combining action and strategy in a unique way,...",https://shared.akamai.steamstatic.com/store_it...

In [39]:
df.head(5)

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
4,914010,Train Station Renovation,"Oct 1, 2020",False,18.99,False,0,Live Motion Games,"Live Motion Games, Frozen Way, PlayWay S.A., F...","Casual, Indie, Simulation",...,"200,000 .. 500,000",448,0,201,16,0,1,73,"Welcome to an old, ruined train station. A pla...",https://shared.akamai.steamstatic.com/store_it...
5,352550,Urban Empire,"Jan 20, 2017",False,2.99,False,90,Reborn Games,Kalypso Media Digital,"Simulation, Strategy",...,"200,000 .. 500,000",114,0,104,3,0,0,74,"Urban Empire is a ‘City Ruler’, pioneering a n...",https://shared.akamai.steamstatic.com/store_it...
11,34330,Total War: SHOGUN 2,"Mar 15, 2011",False,5.99,False,80,"CREATIVE ASSEMBLY, Feral Interactive (Mac), Fe...","SEGA, Feral Interactive (Mac), Feral Interacti...",Strategy,...,"2,000,000 .. 5,000,000",2536,828,402,1807,0,8,106,Total War: SHOGUN 2 is the perfect mix of real...,https://shared.akamai.steamstatic.com/store_it...
13,736260,Baba Is You,"Mar 13, 2019",False,14.99,False,0,Hempuli Oy,Hempuli Oy,Indie,...,"1,000,000 .. 2,000,000",813,120,317,269,0,1,18,Baba Is You is a puzzle game where the rules y...,https://shared.akamai.steamstatic.com/store_it...
15,350640,Sherlock Holmes: The Devil's Daughter,"Jun 10, 2016",False,2.99,False,90,Frogwares,Frogwares,"Action, Adventure",...,"1,000,000 .. 2,000,000",322,0,200,21,0,1,25,Experience a fantastic adventure with unique g...,https://shared.akamai.steamstatic.com/store_it...

In [40]:
df.columns

Index(['app_id', 'name', 'release_date', 'coming_soon', 'price_usd', 'is_free',
       'discount_pct', 'developer', 'publisher', 'genres', 'categories',
       'tags', 'platforms_win', 'platforms_mac', 'platforms_linux',
       'metacritic_score', 'recommendations', 'positive_reviews',
       'negative_reviews', 'estimated_owners', 'avg_playtime_forever',
       'avg_playtime_2weeks', 'median_playtime', 'peak_ccu', 'required_age',
       'dlc_count', 'achievements', 'short_description', 'header_image'],
      dtype='object')

In [41]:
df.sort_values('positive_reviews',ascending=True)

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
967,283390,Incoming + Incoming Forces,"Mar 6, 2014",False,2.99,False,0,Rage Software,Funbox Media Ltd,Action,...,"200,000 .. 500,000",319,0,230,0,0,0,0,Prepare for one of the most action packed-shoo...,https://shared.akamai.steamstatic.com/store_it...
583,2840,X: Beyond the Frontier,"Oct 8, 2010",False,4.99,False,0,Egosoft,Egosoft,"Simulation, Strategy",...,"200,000 .. 500,000",497,141,728,5,0,0,0,The Human Race had advanced to the point where...,https://shared.akamai.steamstatic.com/store_it...
1180,8880,Freedom Force,"May 29, 2009",False,4.99,False,0,Irrational Games,2K,"RPG, Strategy",...,"200,000 .. 500,000",36,0,40,1,0,0,0,"From a distant corner of the galaxy, an evil a...",https://shared.akamai.steamstatic.com/store_it...
101,200390,Oil Rush,"Jan 25, 2012",False,0.00,True,0,Unigine Corp.,Unigine Corp.,"Indie, Strategy",...,"200,000 .. 500,000",128,0,29,0,0,2,40,Oil Rush is a naval strategy game that takes p...,https://shared.akamai.steamstatic.com/store_it...
954,237950,UFO: Afterlight,"Jan 6, 2014",False,6.99,False,0,Altar Games,Bohemia Interactive,"Indie, Strategy",...,"200,000 .. 500,000",111,0,219,7,0,0,0,The story is situated on Mars. It starts where...,https://shared.akamai.steamstatic.com/store_it...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,239140,Dying Light,"Jan 26, 2015",False,24.99,False,0,Techland,Techland,"Action, RPG",...,"10,000,000 .. 20,000,000",2154,297,1073,4953,17,41,78,First-person action survival game set in a pos...,https://shared.akamai.steamstatic.com/store_it...
610,230410,Warframe,"Mar 25, 2013",False,0.00,True,0,Digital Extremes,Digital Extremes,"Action, RPG, Free To Play",...,"20,000,000 .. 50,000,000",14399,1056,550,36195,17,17,193,Awaken as an unstoppable warrior and battle al...,https://shared.akamai.steamstatic.com/store_it...
1228,346110,ARK: Survival Evolved,"Aug 27, 2017",False,9.89,False,34,"Studio Wildcard, Instinct Games, Efecto Studio...","Studio Wildcard, Snail Games USA","Action, Adventure, Indie, Massively Multiplaye...",...,"20,000,000 .. 50,000,000",12691,2303,971,22170,0,18,32,"Stranded on the shores of a mysterious island,...",https://shared.akamai.steamstatic.com/store_it...
193,1086940,Baldur's Gate 3,"Aug 3, 2023",False,59.99,False,0,Larian Studios,Larian Studios,"Adventure, RPG, Strategy",...,"20,000,000 .. 50,000,000",7794,685,4392,54771,17,2,54,"Baldur’s Gate 3 is a story-rich, party-based R...",https://shared.akamai.steamstatic.com/store_it...
578,252490,Rust,"Feb 8, 2018",False,39.99,False,0,Facepunch Studios,Facepunch Studios,"Action, Adventure, Indie, Massively Multiplaye...",...,"20,000,000 .. 50,000,000",20315,1157,3043,143870,0,5,102,The only aim in Rust is to survive. Everything...,https://shared.akamai.steamstatic.com/store_it...

In [44]:
df['release_date'] = pd.to_datetime(df['release_date'])

In [49]:
df[df['release_date'].dt.year > 2023]

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
73,2677660,Indiana Jones and the Great Circle,2024-12-08,False,69.99,False,0,MachineGames,Bethesda Softworks,"Action, Adventure",...,"200,000 .. 500,000",1411,0,1331,274,0,1,55,Uncover one of history’s greatest mysteries in...,https://shared.akamai.steamstatic.com/store_it...
116,1903340,Clair Obscur: Expedition 33,2025-04-24,False,49.99,False,0,Sandfall Interactive,Kepler Interactive,"Action, RPG",...,"2,000,000 .. 5,000,000",2208,889,1819,27880,17,4,55,Lead the members of Expedition 33 on their que...,https://shared.akamai.steamstatic.com/store_it...
155,2072450,Like a Dragon: Infinite Wealth,2024-01-25,False,69.99,False,0,Ryu Ga Gotoku Studio,SEGA,"Action, Adventure, RPG",...,"500,000 .. 1,000,000",3635,63,2029,655,17,19,74,"Two larger-than-life heroes, Ichiban Kasuga an...",https://shared.akamai.steamstatic.com/store_it...
260,1422440,Cataclismo,2025-03-20,False,17.99,False,40,Digital Sun,Hooded Horse,"Simulation, Strategy",...,"200,000 .. 500,000",919,0,413,47,0,0,43,Design and build fortresses brick by brick to ...,https://shared.akamai.steamstatic.com/store_it...
314,1025600,Battle Realms: Zen Edition,2025-01-27,False,14.99,False,0,Ed Del Castillo,Ed Del Castillo,"Action, Strategy",...,"200,000 .. 500,000",1152,0,188,208,0,0,0,"Return of the Classic, now remastered! Battle ...",https://shared.akamai.steamstatic.com/store_it...
323,2273430,BlazBlue Entropy Effect,2024-02-14,False,19.99,False,0,91Act,"91Act, Astrolabe Games","Action, Adventure, Indie",...,"500,000 .. 1,000,000",1036,0,496,1099,0,9,43,Enjoy action-packed flashy combat with incredi...,https://shared.akamai.steamstatic.com/store_it...
326,1062810,Inkbound,2024-04-09,False,29.99,False,0,Shiny Shoe,Shiny Shoe,"Action, Indie, Massively Multiplayer, RPG, Sim...",...,"200,000 .. 500,000",1308,0,829,178,0,4,39,A turn-based tactical roguelike from the creat...,https://shared.akamai.steamstatic.com/store_it...
438,2488620,F1® 24,2024-05-31,False,0.00,False,0,Codemasters,Electronic Arts,"Racing, Sports",...,"500,000 .. 1,000,000",2090,224,1045,2067,0,0,50,Join the grid and Be One of the 20. Drive like...,https://shared.akamai.steamstatic.com/store_it...
567,1735700,Back to the Dawn,2025-07-17,False,23.99,False,0,Metal Head Games,Spiral Up Games,"Adventure, Indie, RPG, Simulation, Strategy",...,"200,000 .. 500,000",1637,13,523,209,0,3,46,Back to the Dawn is a story-rich RPG set in a ...,https://shared.akamai.steamstatic.com/store_it...
603,1601580,Frostpunk 2,2024-09-20,False,22.49,False,50,11 bit studios,11 bit studios,"Simulation, Strategy",...,"500,000 .. 1,000,000",1106,34,624,525,0,3,71,"Develop, expand, and advance your city in a so...",https://shared.akamai.steamstatic.com/store_it...
679,1466060,Tainted Grail: The Fall of Avalon,2025-05-23,False,44.99,False,0,Questline,Awaken Realms,"Action, Adventure, Indie, RPG",...,"200,000 .. 500,000",1654,492,1418,8175,0,5,65,Step into a dark reimagination of Arthurian le...,https://shared.akamai.steamstatic.com/store_it...
692,2183900,"Warhammer 40,000: Space Marine 2",2024-09-09,False,19.79,False,67,Saber Interactive,Focus Entertainment,"Action, Adventure, RPG",...,"5,000,000 .. 10,000,000",1722,278,840,6851,17,22,50,Embody the superhuman skill and brutality of a...,https://shared.akamai.steamstatic.com/store_it...
736,333640,Caves of Qud,2024-12-05,False,29.99,False,0,Freehold Games,Kitfox Games,"Adventure, Indie, RPG, Strategy",...,"200,000 .. 500,000",4558,2,314,425,0,2,150,Inhabit a deeply-simulated science fantasy wor...,https://shared.akamai.steamstatic.com/store_it...
756,1486920,Tempest Rising,2025-04-24,False,39.99,False,0,Slipgate Ironworks™,"3D Realms, Knights Peak, Saber Interactive","Action, Strategy",...,"500,000 .. 1,000,000",728,5,277,528,0,2,98,Command distinct factions in a desperate strug...,https://shared.akamai.steamstatic.com/store_it...
771,1778820,TEKKEN 8,2024-01-25,False,59.99,False,0,Bandai Namco Studios Inc.,Bandai Namco Entertainment,Action,...,"1,000,000 .. 2,000,000",5647,350,1605,4409,0,22,47,TEKKEN 8 is the latest addition to the TEKKEN ...,https://shared.akamai.steamstatic.com/store_it...
1186,784150,Workers & Resources: Soviet Republic,2024-06-20,False,9.99,False,75,3Division,Hooded Horse,"Simulation, Strategy",...,"500,000 .. 1,000,000",935,0,251,2590,0,5,17,Build a soviet republic from an impoverished c...,https://shared.akamai.steamstatic.com/store_it...
1255,1771300,Kingdom Come: Deliverance II,2025-02-04,False,59.99,False,0,Warhorse Studios,Deep Silver,"Action, Adventure, RPG",...,"2,000,000 .. 5,000,000",4594,944,3697,7073,18,10,83,"A thrilling story-driven action RPG, with a ri...",https://shared.akamai.steamstatic.com/store_it...
1268,1159690,Voidtrain,2025-11-07,False,17.99,False,40,HypeTrain Digital,HypeTrain Digital,"Action, Adventure, Indie, RPG, Simulation",...,"200,000 .. 500,000",921,63,550,97,0,3,55,Become a crew member of an Interdimensional Ex...,https://shared.akamai.steamstatic.com/store_it...

In [50]:
df.head(1)

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
4,914010,Train Station Renovation,2020-10-01,False,18.99,False,0,Live Motion Games,"Live Motion Games, Frozen Way, PlayWay S.A., F...","Casual, Indie, Simulation",...,"200,000 .. 500,000",448,0,201,16,0,1,73,"Welcome to an old, ruined train station. A pla...",https://shared.akamai.steamstatic.com/store_it...

In [51]:
df.groupby('genres')['price_usd'].mean()

genres
Action                                                                                              18.235088
Action, Adventure                                                                                   23.014286
Action, Adventure, Casual                                                                           11.240000
Action, Adventure, Casual, Indie                                                                    14.490000
Action, Adventure, Casual, Indie, Massively Multiplayer, RPG, Simulation, Strategy, Free To Play     0.000000
                                                                                                      ...
Simulation, Sports                                                                                   0.000000
Simulation, Strategy                                                                                19.008750
Sports                                                                                               0.000000
Sports, Strategy                                                                                     2.990000
Strategy                                                                                            12.260500
Name: price_usd, Length: 115, dtype: float64

In [53]:
df.groupby('genres')['price_usd'].mean().max()

49.99

In [54]:
df.groupby('genres')['name'].count()

genres
Action                                                                                              57
Action, Adventure                                                                                   42
Action, Adventure, Casual                                                                            4
Action, Adventure, Casual, Indie                                                                     2
Action, Adventure, Casual, Indie, Massively Multiplayer, RPG, Simulation, Strategy, Free To Play     1
                                                                                                    ..
Simulation, Sports                                                                                   3
Simulation, Strategy                                                                                16
Sports                                                                                               1
Sports, Strategy                                                                                     1
Strategy                                                                                            20
Name: name, Length: 115, dtype: int64

In [57]:
df.groupby('genres')['name'].count().sort_values(ascending=False)

genres
Action                                                                                              57
Action, Adventure                                                                                   42
Adventure, Indie                                                                                    27
Action, Adventure, Indie                                                                            26
Action, Indie                                                                                       25
                                                                                                    ..
Adventure, Indie, Massively Multiplayer, RPG, Strategy                                               1
Action, Adventure, Casual, Indie, Massively Multiplayer, RPG, Simulation, Strategy, Free To Play     1
Adventure, Indie, RPG, Simulation                                                                    1
Action, Free To Play, Strategy                                                                       1
Action, Adventure, Casual, Indie, RPG, Strategy                                                      1
Name: name, Length: 115, dtype: int64

In [61]:
df.sort_values('price_usd',ascending=False).head(5)

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
155,2072450,Like a Dragon: Infinite Wealth,2024-01-25,False,69.99,False,0,Ryu Ga Gotoku Studio,SEGA,"Action, Adventure, RPG",...,"500,000 .. 1,000,000",3635,63,2029,655,17,19,74,"Two larger-than-life heroes, Ichiban Kasuga an...",https://shared.akamai.steamstatic.com/store_it...
73,2677660,Indiana Jones and the Great Circle,2024-12-08,False,69.99,False,0,MachineGames,Bethesda Softworks,"Action, Adventure",...,"200,000 .. 500,000",1411,0,1331,274,0,1,55,Uncover one of history’s greatest mysteries in...,https://shared.akamai.steamstatic.com/store_it...
1220,924970,Back 4 Blood,2021-10-12,False,59.99,False,0,Turtle Rock Studios,Warner Bros. Games,Action,...,"1,000,000 .. 2,000,000",1558,52,607,1288,17,4,93,Back 4 Blood is a thrilling cooperative first-...,https://shared.akamai.steamstatic.com/store_it...
822,209650,Call of Duty®: Advanced Warfare - Gold Edition,2014-11-03,False,59.99,False,0,"Sledgehammer Games, Raven Software",Activision,Action,...,"200,000 .. 500,000",506,34,413,63,17,43,45,Call of Duty®: Advanced Warfare envisions a po...,https://shared.akamai.steamstatic.com/store_it...
361,1382330,Persona® 5 Strikers,2021-02-22,False,59.99,False,0,ATLUS,SEGA,"Action, Adventure",...,"1,000,000 .. 2,000,000",995,0,454,199,17,2,47,Join the Phantom Thieves and strike back again...,https://shared.akamai.steamstatic.com/store_it...

In [62]:
df.columns

Index(['app_id', 'name', 'release_date', 'coming_soon', 'price_usd', 'is_free',
       'discount_pct', 'developer', 'publisher', 'genres', 'categories',
       'tags', 'platforms_win', 'platforms_mac', 'platforms_linux',
       'metacritic_score', 'recommendations', 'positive_reviews',
       'negative_reviews', 'estimated_owners', 'avg_playtime_forever',
       'avg_playtime_2weeks', 'median_playtime', 'peak_ccu', 'required_age',
       'dlc_count', 'achievements', 'short_description', 'header_image'],
      dtype='object')

In [63]:
df.sort_values('positive_reviews',ascending=False).head(5)

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
578,252490,Rust,2018-02-08,False,39.99,False,0,Facepunch Studios,Facepunch Studios,"Action, Adventure, Indie, Massively Multiplaye...",...,"20,000,000 .. 50,000,000",20315,1157,3043,143870,0,5,102,The only aim in Rust is to survive. Everything...,https://shared.akamai.steamstatic.com/store_it...
193,1086940,Baldur's Gate 3,2023-08-03,False,59.99,False,0,Larian Studios,Larian Studios,"Adventure, RPG, Strategy",...,"20,000,000 .. 50,000,000",7794,685,4392,54771,17,2,54,"Baldur’s Gate 3 is a story-rich, party-based R...",https://shared.akamai.steamstatic.com/store_it...
1228,346110,ARK: Survival Evolved,2017-08-27,False,9.89,False,34,"Studio Wildcard, Instinct Games, Efecto Studio...","Studio Wildcard, Snail Games USA","Action, Adventure, Indie, Massively Multiplaye...",...,"20,000,000 .. 50,000,000",12691,2303,971,22170,0,18,32,"Stranded on the shores of a mysterious island,...",https://shared.akamai.steamstatic.com/store_it...
610,230410,Warframe,2013-03-25,False,0.00,True,0,Digital Extremes,Digital Extremes,"Action, RPG, Free To Play",...,"20,000,000 .. 50,000,000",14399,1056,550,36195,17,17,193,Awaken as an unstoppable warrior and battle al...,https://shared.akamai.steamstatic.com/store_it...
960,239140,Dying Light,2015-01-26,False,24.99,False,0,Techland,Techland,"Action, RPG",...,"10,000,000 .. 20,000,000",2154,297,1073,4953,17,41,78,First-person action survival game set in a pos...,https://shared.akamai.steamstatic.com/store_it...